### ISSUE TITLE
Sugestão para nome... search-github? já pensou em gitsearch? 

### ISSUE THREAD

**Issue by pglapds** [valmisson/gitsearch#2]
Sugestão para nome... search-github? já pensou em gitsearch?

**Comment by valmisson** [comment]
Gostei do nome, Obrigado pela sugestão

**Comment by pglapds** [comment]
> Gostei do nome, Obrigado pela sugestão

Valeu. **^^**

**Comment by valmisson** [comment]
Não da para mudar a url ela já esta em uso

**Comment by pglapds** [comment]
> 
> 
> Não da para mudar a url ela já esta em uso

Okay.
