### ISSUE TITLE
Incluir todos os repositórios de usuários

### ISSUE THREAD

**Issue by ghost** [valmisson/gitsearch#3]
Exemplo... digito ***Paulo*** ... deveria mostrar o repositório **Paulo** ou em outro caso os repositórios desse usuário também.

**Comment by valmisson** [comment]
Já tinha essa feature em mente, até comecei desenvolver ele no começo do projeto, retirei por causa que eu não tinha tempo disponível para implementa

**Comment by pglapds** [comment]
> 
> 
> Já tinha essa feature em mente, até comecei desenvolver ele no começo do projeto, retirei por causa que eu não tinha tempo disponível para implementa

Interessante. PS: Vou ver se ajudo nesse ponto.
